const colorSelector = {
  multi: [
    "#202020",
    "White",
    "Orange",
    "Violet",
    "Brown",
    "Aqua",
    "Pink",
    "Navy",
    "Purple",
    "Coral",
    "Grey",
    "DarkOrange",
    "LightBlue",
    "LightGreen",
    "Magenta",
    "Navy",
    "PeachPuff",
    "RebeccaPurple",
    "RoyalBlue",
    "Silver",
    "SteelBlue",
    "Turquoise",
    "MediumPurple",
    "MidnightBlue",
    "LimeGreen",
    "Khaki",
    "Ivory",
    "DarkSlateGrey",
  ],
  basic: ["#202020", "white"],
  black: ["#202020"],
  white: ["white"],
};

export default colorSelector;
